import { buildUrl, defineIntegration, fetchJson, makeProvenance, type EnvLike, type HealthResult, type OperationContext } from "../framework";

/**
 * SolarEdge Monitoring Server API.
 *
 * Endpoints, `api_key` query parameter, `YYYY-MM-DD HH:MM:SS` time format and meter
 * names confirmed from the open-source aiosolaredge client and Homey SolarEdge driver
 * types; response envelopes (sites.site[], energy.values[], energyDetails.meters[],
 * overview.*) follow the published Monitoring API guide. Not exercised live from here.
 */

const BASE = "https://monitoringapi.solaredge.com";
const MAX_DAY_RANGE_DAYS = 366;
const MAX_SUBDAY_RANGE_DAYS = 31;

interface Site {
  id: number;
  name: string;
  accountId?: number;
  status?: string;
  peakPower?: number;
  lastUpdateTime?: string;
  installationDate?: string;
  type?: string;
  location?: { country?: string; city?: string; address?: string; zip?: string; timeZone?: string };
}

interface SitesList {
  sites: { count: number; site: Site[] };
}

interface Overview {
  overview: {
    lastUpdateTime?: string;
    lifeTimeData?: { energy?: number; revenue?: number };
    lastYearData?: { energy?: number };
    lastMonthData?: { energy?: number };
    lastDayData?: { energy?: number };
    currentPower?: { power?: number };
    measuredBy?: string;
  };
}

interface Energy {
  energy: { timeUnit: string; unit: string; measuredBy?: string; values: { date: string; value: number | null }[] };
}

interface EnergyDetails {
  energyDetails: { timeUnit: string; unit: string; meters: { type: string; values: { date: string; value?: number | null }[] }[] };
}

function apiKey(env: EnvLike): string {
  const k = env.SOLAREDGE_API_KEY?.trim();
  if (!k) throw new Error("SOLAREDGE_API_KEY is not set");
  return k;
}

function toKwh(value: number | null | undefined, unit: string): number | null {
  if (value === null || value === undefined || !Number.isFinite(value)) return null;
  const u = unit.toLowerCase();
  const kwh = u === "wh" ? value / 1000 : u === "mwh" ? value * 1000 : value;
  return Math.round(kwh * 1000) / 1000;
}

function daysBetween(start: string, end: string): number {
  return Math.round((Date.parse(end + "T00:00:00Z") - Date.parse(start + "T00:00:00Z")) / 86_400_000);
}

function assertRange(start: string, end: string, maxDays: number, label: string) {
  const n = daysBetween(start, end);
  if (Number.isNaN(n)) throw new Error("Dates must be valid YYYY-MM-DD");
  if (n < 0) throw new Error("end_date must be on or after start_date");
  if (n + 1 > maxDays) throw new Error(`${label} is limited to ${maxDays} days per request by SolarEdge`);
}

const SITE_ID = { name: "site_id", label: "Site ID", type: "integer", required: true, placeholder: "1234567", min: 1 } as const;

const METER_KEY: Record<string, string> = { production: "production_kwh", consumption: "consumption_kwh", feedin: "export_kwh", purchased: "import_kwh", selfconsumption: "self_consumption_kwh" };

export const definition = defineIntegration({
  id: "solaredge",
  name: "SolarEdge Monitoring",
  group: "solar",
  access: "authorised",
  territory: "Global",
  description: "Metered generation, consumption, import and export from SolarEdge inverter sites via the owner's or installer's monitoring API key.",
  docsUrl: "https://knowledge-center.solaredge.com/sites/kc/files/se_monitoring_api.pdf",
  termsUrl: "https://www.solaredge.com/us/legal/terms-of-use",
  attribution: "Site energy data from the SolarEdge Monitoring API, provided under the site owner's authorisation.",
  licence: "consent_based",
  envVars: [{ name: "SOLAREDGE_API_KEY", required: true, description: "Monitoring API key (account or site level) generated by the site owner or installer in the SolarEdge monitoring platform (Admin > Site Access > API Access). Sent as the api_key query parameter." }],
  status: "built_unverified",
  notes: [
    "The client (site owner) must generate the key and consent to the portal reading their data; record the consent reference in the provenance.",
    "Rate limit: 300 requests per day per site per key (account-level keys are also limited to 300 per day per site). Cache daily pulls.",
    "energyDetails at QUARTER_OF_AN_HOUR or HOUR resolution is limited to one month per call; DAY resolution to one year. This connector enforces the same limits before calling.",
    "Times are in the site's local time zone. Energy units follow the response's unit field (usually Wh) and are converted to kWh here.",
    "Consumption, import and export meters only appear when the site has a SolarEdge energy meter; rows show null for absent meters.",
    "Not exercised live from this environment.",
  ],
  healthCheck: async (ctx: OperationContext): Promise<HealthResult> => {
    const started = Date.now();
    try {
      const { data } = await fetchJson<SitesList>(ctx, buildUrl(BASE, "sites/list", { size: 1, api_key: apiKey(ctx.env) }), {}, { timeoutMs: 15_000 });
      return { ok: typeof data.sites?.count === "number", detail: `${data.sites?.count ?? "?"} sites visible to this key`, latencyMs: Date.now() - started };
    } catch (e) {
      return { ok: false, detail: e instanceof Error ? e.message : String(e), latencyMs: Date.now() - started };
    }
  },
  operations: [
    {
      id: "sites",
      label: "List sites",
      description: "Sites visible to the API key, with peak power and status.",
      params: [],
      async run(_params, ctx) {
        const { data } = await fetchJson<SitesList>(ctx, buildUrl(BASE, "sites/list", { size: 100, api_key: apiKey(ctx.env) }));
        const columns = ["site_id", "name", "status", "peak_power_kwp", "installation_date", "city", "postcode", "last_update"];
        const rows = (data.sites?.site ?? []).map((s) => ({ site_id: s.id, name: s.name, status: s.status ?? null, peak_power_kwp: s.peakPower ?? null, installation_date: s.installationDate ?? null, city: s.location?.city ?? null, postcode: s.location?.zip ?? null, last_update: s.lastUpdateTime ?? null }));
        const kwp = rows.reduce((a, r) => a + (r.peak_power_kwp ?? 0), 0);
        return {
          summary: rows.length ? `${data.sites.count} site(s), ${rows.length} listed, ${Math.round(kwp * 10) / 10} kWp in total.` : "No sites visible to this key.",
          columns,
          rows,
          raw: data,
          provenance: makeProvenance(definition, ctx, { dataset: "sites/list", basis: rows.length ? "client_declared" : "unavailable" }),
        };
      },
    },
    {
      id: "site-overview",
      label: "Site overview",
      description: "Lifetime, last-year, last-month and last-day energy plus current power for a site.",
      params: [SITE_ID],
      async run(params, ctx) {
        const id = Number(params.site_id);
        const { data } = await fetchJson<Overview>(ctx, buildUrl(BASE, `site/${id}/overview`, { api_key: apiKey(ctx.env) }));
        const o = data.overview;
        const columns = ["site_id", "last_update", "lifetime_kwh", "last_year_kwh", "last_month_kwh", "last_day_kwh", "current_power_kw"];
        if (!o) return { summary: `No overview returned for site ${id}.`, columns, rows: [], raw: data, provenance: makeProvenance(definition, ctx, { dataset: "site/overview", basis: "unavailable" }) };
        const row = {
          site_id: id,
          last_update: o.lastUpdateTime ?? null,
          lifetime_kwh: toKwh(o.lifeTimeData?.energy, "Wh"),
          last_year_kwh: toKwh(o.lastYearData?.energy, "Wh"),
          last_month_kwh: toKwh(o.lastMonthData?.energy, "Wh"),
          last_day_kwh: toKwh(o.lastDayData?.energy, "Wh"),
          current_power_kw: o.currentPower?.power !== undefined ? Math.round(o.currentPower.power) / 1000 : null,
        };
        return {
          summary: `Site ${id}: ${row.lifetime_kwh ?? "?"} kWh lifetime, ${row.last_month_kwh ?? "?"} kWh in the last month, ${row.last_day_kwh ?? "?"} kWh yesterday/today; current power ${row.current_power_kw ?? "?"} kW at ${row.last_update ?? "unknown time"}.`,
          columns,
          rows: [row],
          raw: data,
          provenance: makeProvenance(definition, ctx, { dataset: "site/overview", basis: "measured" }),
          warnings: ["Overview energies are inverter production (or the site meter where measuredBy says so); consumption and export need the energy-details operation."],
        };
      },
    },
    {
      id: "daily-energy",
      label: "Daily energy for a site",
      description: "Daily production (kWh) for a site over a date range of up to one year.",
      params: [SITE_ID, { name: "start_date", label: "Start date", type: "date", required: true, placeholder: "2025-01-01" }, { name: "end_date", label: "End date", type: "date", required: true, placeholder: "2025-12-31" }],
      async run(params, ctx) {
        const id = Number(params.site_id);
        const start = String(params.start_date);
        const end = String(params.end_date);
        assertRange(start, end, MAX_DAY_RANGE_DAYS, "Daily energy");
        const { data } = await fetchJson<Energy>(ctx, buildUrl(BASE, `site/${id}/energy`, { timeUnit: "DAY", startDate: start, endDate: end, api_key: apiKey(ctx.env) }));
        const unit = data.energy?.unit ?? "Wh";
        const rows = (data.energy?.values ?? []).map((v) => ({ date: v.date.slice(0, 10), energy_kwh: toKwh(v.value, unit) }));
        const columns = ["date", "energy_kwh"];
        if (!rows.length) return { summary: `No daily energy for site ${id} between ${start} and ${end}.`, columns, rows: [], raw: data, provenance: makeProvenance(definition, ctx, { dataset: "site/energy", basis: "unavailable" }) };
        const total = rows.reduce((a, r) => a + (r.energy_kwh ?? 0), 0);
        const missing = rows.filter((r) => r.energy_kwh === null).length;
        return {
          summary: `Site ${id}: ${Math.round(total)} kWh over ${rows.length} days (${start} to ${end})${missing ? `, ${missing} day(s) without a reading` : ""}.`,
          columns,
          rows,
          raw: data,
          provenance: makeProvenance(definition, ctx, { dataset: "site/energy", basis: "measured" }),
          warnings: missing ? ["Days with null values are gaps in communication, not zero generation."] : undefined,
        };
      },
    },
    {
      id: "energy-details",
      label: "Energy by meter (production, consumption, import, export)",
      description: "Production, consumption, export (feed-in) and import (purchased) energy per interval for a site.",
      params: [
        SITE_ID,
        { name: "start_date", label: "Start date", type: "date", required: true, placeholder: "2025-06-01" },
        { name: "end_date", label: "End date", type: "date", required: true, placeholder: "2025-06-30" },
        { name: "time_unit", label: "Resolution", type: "select", default: "DAY", options: [{ value: "QUARTER_OF_AN_HOUR", label: "15 minutes (max 1 month)" }, { value: "HOUR", label: "Hourly (max 1 month)" }, { value: "DAY", label: "Daily (max 1 year)" }] },
      ],
      async run(params, ctx) {
        const id = Number(params.site_id);
        const start = String(params.start_date);
        const end = String(params.end_date);
        const timeUnit = String(params.time_unit ?? "DAY");
        assertRange(start, end, timeUnit === "DAY" ? MAX_DAY_RANGE_DAYS : MAX_SUBDAY_RANGE_DAYS, `${timeUnit} energy detail`);
        const url = buildUrl(BASE, `site/${id}/energyDetails`, { meters: "PRODUCTION,CONSUMPTION,FEEDIN,PURCHASED", timeUnit, startTime: `${start} 00:00:00`, endTime: `${end} 23:59:59`, api_key: apiKey(ctx.env) });
        const { data } = await fetchJson<EnergyDetails>(ctx, url, {}, { timeoutMs: 30_000 });
        const unit = data.energyDetails?.unit ?? "Wh";
        const columns = ["time", "production_kwh", "consumption_kwh", "export_kwh", "import_kwh"];
        const byTime = new Map<string, Record<string, unknown>>();
        const present = new Set<string>();
        for (const m of data.energyDetails?.meters ?? []) {
          const key = METER_KEY[m.type.toLowerCase()];
          if (!key) continue;
          present.add(key);
          for (const v of m.values ?? []) {
            const row = byTime.get(v.date) ?? { time: v.date, production_kwh: null, consumption_kwh: null, export_kwh: null, import_kwh: null };
            row[key] = toKwh(v.value, unit);
            byTime.set(v.date, row);
          }
        }
        const rows = [...byTime.values()].sort((a, b) => String(a.time).localeCompare(String(b.time)));
        if (!rows.length) return { summary: `No energy details for site ${id} between ${start} and ${end}.`, columns, rows: [], raw: data, provenance: makeProvenance(definition, ctx, { dataset: "site/energyDetails", basis: "unavailable" }) };
        const sum = (k: string) => Math.round(rows.reduce((a, r) => a + (Number(r[k]) || 0), 0));
        const warnings: string[] = [];
        for (const k of ["consumption_kwh", "export_kwh", "import_kwh"]) if (!present.has(k)) warnings.push(`No ${k.replace("_kwh", "")} meter on this site; that column is null.`);
        return {
          summary: `Site ${id}, ${start} to ${end} (${timeUnit.toLowerCase().replace(/_/g, " ")}): production ${sum("production_kwh")} kWh, consumption ${present.has("consumption_kwh") ? sum("consumption_kwh") : "n/a"} kWh, export ${present.has("export_kwh") ? sum("export_kwh") : "n/a"} kWh, import ${present.has("import_kwh") ? sum("import_kwh") : "n/a"} kWh.`,
          columns,
          rows,
          raw: data,
          provenance: makeProvenance(definition, ctx, { dataset: "site/energyDetails", basis: "measured" }),
          warnings: warnings.length ? warnings : undefined,
        };
      },
    },
  ],
});
